packages := acl2 \
            arch-tla
            bash \
            bbdb \
            bibtex2html \
            bibtool \
            bitlbee \
            bst-mode \
            bzr \
            camlp5 \
            carbon-emacs-el \
            clisp \
            color-theme \
            coq \
            coreutils \
            diction \
            dpkg \
            dvc \
            ebib \
            edb \
            elinks \
            elip \
            elisp-manual \
            emacs22-carbon \
            emacs23 \
            eon \
            eprover \
            erc \
            file \
            getopt-euclid \
            ghc \
            git \
            gnumeric \
            gprolog \
            hol \
            hol-light \
            htmlize-el \
            hyperspec \
            icon \
            ikiwiki \
            isabelle \
            ledger \
            less \
            m4 \
            mac-key-mode \
            mc \
            mizar \
            moscow-ml \
            mptp \
            muse-el \
            ngnus \
            noweb \
            openproofpower \
            org-mode \
            otter \
            paradox-equinox \
            parallel \
            picons \
            planner-el \
            polyml \
            prover9 \
            r6rs \
            redo-el \
            remember-el \
            sbcl \
            scheme48 \
            screen \
            scsh \
            session-el \
            sicp \
            smart-comments \
            spass \
            sqlite3 \
            system-tetex \
            test \
            texmacs \
            tptp \
            tuareg-mode \
            vala \
            wesnoth \
            wwwoffle \
            xhtml-dtd \
            xtla \
            yap

.PHONY: clean

clean:
