packages := mizar-gab-html \
            mizar-gab \
            mizar-i386 \
            mizar-mode \
            mizar-powerpc \
            mizar-semantic-mml \
            mizar-x86_64 \
            mmlquery-data \
            mmlquery
